### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ghost** [sleeptillseven/stoffel-an-epitome-of-the-new-testament#14]
My last 4 pull requests were never accepted (a few from 6 months ago, and a few now this year).

I am not sure if there is some technical reason they weren't accepted, perhaps I am making a mistake. Or perhaps its just that no one is looking at this any more?

**Comment by seumasjeltzz** [comment]
As far as I know it is technically still alive, but I don't know how much it's being monitored

**Comment by zaddok** [comment]
There is some kind of error when I tryto push. It looks like some kind of custom python thing that I don’t understand.

**Comment by sleeptillseven** [comment]
It is, I just don't have so much free time anymore :(

**Comment by sleeptillseven** [comment]
> There is some kind of error when I tryto push. It looks like some kind of custom python thing that I don’t understand.

Yes, there is a hook which check the formatting of the characters to be compliant to `UTF-8`.

**Comment by ghost** [comment]
I hear you about free time. Thats actually why I was checking. (Creating all of those little pull requests is time consuming, and I was just a little worried I was doing it for no reason.)

I am a little surprised the document isn't already UTF-8. I wonder what encoding it is.
