### ISSUE TITLE
errata for 13

### ISSUE THREAD

**Issue by seumasjeltzz** [sleeptillseven/stoffel-an-epitome-of-the-new-testament#4]
13.title The Magi at the Crib of Bethlehem.

I think this title is wrong? Or at least one version has "The Adoration of the Magi"

In 13.4 you have ἀνεχώρῆσαν , which has been double-accented. It should be ἀνεχώρησαν

**Comment by sleeptillseven** [comment]
Edition 1: The Magi at the Crib of Bethlehem
Edition 2: The Adoration of the Magi

As I prefer the second edition, I'll change it to that. Thanks.
