### ISSUE TITLE
errata for 14

### ISSUE THREAD

**Issue by seumasjeltzz** [sleeptillseven/stoffel-an-epitome-of-the-new-testament#5]
14.1 Ἰωσὴφ should replace Ἰωσήφ
14.4 the first τὸν should be accented grave. also ἐν εἰρήνῃ in place of ἔν εἰρήνῃ

**Comment by sleeptillseven** [comment]
Hi @seumasjeltzz,

thanks for the corrections. Concerning the τον in 14.4, in the second edition it is really missing in the manuscript. In first it's correct τὸν.
